source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Rails
gem 'rails', '~> 5.1.3'

# Files attachments
gem 'carrierwave'

# Authentication
gem 'devise'

# Test
group :test do
  gem 'cucumber-rails', require: false
  gem 'shoulda-matchers', require: false
end

# Test & Development
group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'capybara', '~> 2.15.0'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'rspec-html-matchers'
  gem 'database_cleaner', "~> 1.6", ">= 1.6.1"
  gem 'guard-rspec', "~> 4.7", ">= 4.7.3", require: false
  gem 'awesome_print', "~> 1.8", require: "ap"
  gem 'factory_girl_rails'
end

# Development
group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'webpacker'

  # Better errors handler
  gem 'better_errors', '~> 2.1.0'
  gem 'binding_of_caller', '~> 0.7.2'
end

# Production
group :production do
  gem 'mysql2', '>= 0.3.18', '< 0.5'
  gem 'puma', '~> 3.7'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]